# Set this to allow Magic to set the SHA hash of your resource pack
# automatically on startup.
# Turn this off if you don't need it, but you will then need to manually
# change the name or the SHA of your RP whenever it changes.
enable_resource_pack_check: true

# This resource pack will automatically be used if none is defined in your server.properties
# Set this to "" if you have some other plugin or Bungee managing resource packs.
default_resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-6-1.zip"

# Set this to false to turn off the player skull-based spell icons
# This may be needed if you have disabled the RP, spell icons are in the RP.
url_icons_enabled: false
