#
# Set up for a Star Wars themed server
#

load_default_spells: true
disable_default_spells: true
load_default_wands: true
disable_default_wands: true
load_default_classes: true
load_default_paths: false
load_default_crafting: false
enable_crafting: true

# Disable the enchantment table showing the spell shop or upgrades
enchant_block: ""

# Force power FX come from the hands
wand_location_offset_vertical: -0.5

# Default class
default_mage_class: force_user