#
# Set up for a Star Wars themed server
#

load_default_spells: true
disable_default_spells: true
load_default_wands: false
load_default_enchanting: false
load_default_crafting: false
enable_crafting: true
enable_enchanting: true

# Don't allow combining
enable_combining: false
# Wands don't glow
wand_glow: false

# Force power FX come from the hands
wand_location_offset_vertical: -0.5

# Use the stars RP
default_resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-stars-RP-6.zip"
