# .
# !! IMPORTANT !!
# .
# If you wish to customize this plugin, edit the "config.yml" file instead.
# .
# DO NOT JUST COPY THIS WHOLE FILE INTO YOUR config.yml !!!!
# If you do this, updating the plugin in the future may not work as expected.
# .
# This file is merged from the files in the following folder:
# .
# https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/resources/defaults/config
# .
# .
# This turns on the survival configs by default.
# .
# Set
# example: ""
# in your config.yml to turn this off.
# .

example: survival
