# These are player skins that represent mobs. Some are provided here
# as official Mojang skins, but more can be added.
mob_skins:
  blaze: MHF_Blaze
  cave_spider: MHF_CaveSpider
  chicken: MHF_Chicken
  cow: MHF_Cow
  enderman: MHF_Enderman
  ghast: MHF_Ghast
  iron_golem: MHF_Golem
  magma_cube: MHF_LavaSlime
  mushroom_cow: MHF_MushroomCow
  ocelot: MHF_Ocelot
  pig: MHF_Pig
  pig_zombie: MHF_PigZombie
  sheep: MHF_Sheep
  slime: MHF_Slime
  spider: MHF_Spider
  squid: MHF_Squid
  villager: MHF_Villager
  wolf: MHF_Wolf
  creeper: MHF_Creeper
  zombie: MHF_Zombie
  skeleton: MHF_Skeleton
  guardian: MHF_Guardian
  witch: MHF_Witch