#
# Set up for an Avatar (bending) server.
#

# This is a modifier on the default survival configs
inherit: survival

# Turn off the survival spells, but allow them to be inherited from
disable_inherited:
 - spells

skip_inherited:
 - wands
 - paths
 - crafting
 - classes
 - mobs

# Don't allow crafting
enable_crafting: false

# Configure some custom damage types
damage_types:
  earth:
    max_reduction: 0.5
    max_strength: 5
    max_weakness: 10
  fire:
    max_reduction: 0.5
    max_strength: 5
    max_weakness: 10
  air:
    max_reduction: 0.5
    max_strength: 5
    max_weakness: 10
  water:
    max_reduction: 0.5
    max_strength: 5
    max_weakness: 10

# Default class
default_mage_class: bender