#
# The default path is a base path common to the others
#

default:
  hidden: true
  upgrade_commands:
    - broadcast &6@pd &3has advanced to &b$path&3!
  effects:
      # These effects will play when a wand is modified as a result of being
      # enchanted or buying a spell.
      # This doesn't really happen anymore with the default configs, the spellshop
      # is responsible for playing effects on purchase.
      enchant:
      -  class: EffectSingle
         sound: entity_player_levelup
         effectlib:
           class: SphereEffect
           iterations: 5
           period: 2
           particle: enchantment_table
           radius: 3
      upgrade:
      -  class: EffectSingle
         sound: entity_player_levelup
      -  class: EffectRing
         firework: star
         radius: 4
         size: 2
      -  class: EffectRing
         firework: ball_large
         radius: 6
         size: 3

