general:
    silent: false
    building:
    - air
    - stone
    - grass
    - dirt
    - cobblestone
    - wood
    - bedrock
    - water
    - stationary_water
    - lava
    - stationary_lava
    - sand
    - gravel
    - gold_ore
    - iron_ore
    - coal_ore
    - log
    - leaves
    - sponge
    - glass
    - lapis_ore
    - lapis_block
    - dispenser
    - sandstone
    - note_block
    - bed_block
    - powered_rail
    - detector_rail
    - piston_sticky_base
    - piston_base
    - piston_extension
    - wool
    - gold_block
    - iron_block
    - double_step
    - brick
    - tnt
    - bookshelf
    - mossy_cobblestone
    - obsidian
    - mob_spawner
    - wood_stairs
    - redstone_wire
    - diamond_ore
    - diamond_block
    - workbench
    - soil
    - furnace
    - burning_furnace
    - ladder
    - rails
    - cobblestone_stairs
    - redstone_ore
    - glowing_redstone_ore
    - ice
    - snow_block
    - cactus
    - clay
    - sugar_cane_block
    - jukebox
    - fence
    - pumpkin
    - netherrack
    - soul_sand
    - glowstone
    - portal
    - jack_o_lantern
    - cake_block
    - diode_block_off
    - diode_block_on
    - locked_chest
    - trap_door
    - monster_eggs
    - smooth_brick
    - huge_mushroom_1
    - huge_mushroom_2
    - iron_fence
    - thin_glass
    - melon_block
    - pumpkin_stem
    - melon_stem
    - vine
    - fence_gate
    - brick_stairs
    - smooth_stairs
    undo_depth: 256
    quiet: true
