name: Magic
main: com.elmakers.mine.bukkit.plugins.magic.MagicPlugin
version: 2.4.1
website: http://mine.elmakers.com
author: NathanWolf
description : Mmmmmmaaaaagic!
softdepend: [WorldGuard]
load: startup
commands:
  cast:
    description: Cast a spell directly
    usage: cast <spellname>
    permission: Magic.commands.cast
  spells:
    description: List all the spells you know
    usage: spells [category]
    permission: Magic.commands.spells
  wand:
    description: Create and modify wands
    usage: /wand [add|remove] [spell]
    permission: Magic.commands.wand
  magic:
    description: Administer the Magic plugin
    usage: /magic [reload|reset]
    permission: Magic.commands.magic
permissions:
  Magic.commands.spells:
    description: Player may list spells
    type: boolean
    default: op
  Magic.commands.cast:
    description: Player may cast command-line spells
    type: boolean
    default: op
  Magic.commands.wand:
    description: Player may create a wand
    type: boolean
    default: op
  Magic.commands.wand.list:
    description: Player may list available wand templates
    type: boolean
    default: op
  Magic.commands.wand.add:
    description: Player may add a spell to a wand
    type: boolean
    default: op
  Magic.commands.wand.configure:
    description: Player may set wand properties
    type: boolean
    default: op
  Magic.commands.wand.remove:
    description: Player may remove a spell from a wand
    type: boolean
    default: op
  Magic.commands.wand.name:
    description: Player may name a wand
    type: boolean
    default: op
  Magic.commands.magic.reset:
    description: Player may reset spells to defaults
    type: boolean
    default: op
  Magic.commands.magic.reload:
    description: Player may reload the configuration
    type: boolean
    default: op
  Magic.wand.use:
    description: The player may use a wand
    default: true
    type: boolean
  Magic.cast:
    description: The spells a player may cast
    type: list