name: Magic
main: com.elmakers.mine.bukkit.plugins.magic.MagicPlugin
version: 2.2.0
website: http://mine.elmakers.com
author: NathanWolf
description : Mmmmmmaaaaagic!
commands:
  cast:
    description: Cast a spell directly
    usage: cast <spellname>
  spells:
    description: List all the spells you know
    usage: spells [category]
  wand:
    description: Create and modify wands
    usage: /wand [add|remove] [spell]
  magic:
    description: Administer the Magic plugin
    usage: /magic [reload|reset]
permissions:
  Magic:
    description: Magic permissions
    type: map
    map:
      commands:
        description: Magic console command permissions
        type: map
        map:
          spells:
            description: Player may list spells
            type: boolean
            default: false
          cast:
            description: Player may cast command-line spells
            type: boolean
            default: false
          wand:
            description: Player may create and modify wands
            type: boolean
            default: false
            map:
              add:
                description: Player may add spells to a wand
                type: boolean
                default: false;
              remove:
                description: Player may remove spells from a wand
                type: boolean
                default: false;
              name:
                description: Player may rename  wand
                type: boolean
                default: false;
          magic:
            description: Player may use administration commands for Magic
            type: map
            map:
              reset:
                description: Player may reset spells to defaults
                type: boolean
                default: false;
              reload:
                description: Player may reload the configuration
                type: boolean
                default: false;
      cast:
        description: The spells a player may cast
        type: list
      wand:
        description: Wand-related permissoins
        type: map
        map:
          use:
            description: Player may use a wand
            type: boolean
            default: true