name: Magic
main: com.elmakers.mine.bukkit.magic.MagicPlugin
version: ${project.version}
website: http://mine.elmakers.com
author: NathanWolf
description : Mmmmmmaaaaagic!
softdepend: [WorldGuard,WorldEdit,Essentials,dynmap,dtlTraders,Factions,CommandBook,PvPManager,Multiverse-Core,WGCustomFlags,Citizens]
commands:
  cast:
    aliases: [mcast]
    description: Cast a spell directly
    usage: cast <spellname> [parameters]
    permission: Magic.commands.cast
  castp:
    aliases: [mcastp]
    description: Cast a spell directly on another player
    usage: castp <player> <spellname> [parameters]
    permission: Magic.commands.cast
  spells:
    aliases: [mspells]
    description: List all the spells you know
    usage: spells [category]
    permission: Magic.commands.spells
  wand:
    description: Create and modify wands
    usage: /wand [add|remove|upgrade|configure|describe|organize|enchant|unenchant|duplicate|unlock|override] [<spellname>|material] <materialname>
    permission: Magic.commands.wand
  wandp:
    description: Create and modify wands for another player
    usage: /wandp <player> [add|remove|upgrade|configure|describe|organize|enchant|unenchant|duplicate|unlock|override] [<spellname>|material] <materialname>
    permission: Magic.commands.wandp
  magic:
    description: Administer the Magic plugin
    usage: /magic [load|save|cancel|clearcache|commit|list|give]
    permission: Magic.commands.magic
  mgive:
    description: Give players items
    usage: /mgive <Player> [itemname] <amount>
    permission: Magic.commands.mgive
  mtrait:
    description: Manage Magic NPCs
    usage: /mtrait <id#> <property> <value>
    permission: Magic.commands.mtrait
permissions:
  Magic.commands.spells:
    description: Player may list spells
    type: boolean
    default: op
  Magic.commands.mgive:
    description: Player may give out magic items
    type: boolean
    default: op
  Magic.commands.mtrait:
    description: Player may manage Magic NPCs
    type: boolean
    default: op
  Magic.commands.cast:
    description: Player may cast command-line spells
    type: boolean
    default: op
  Magic.commands.castp:
    description: Player may cast command-line spells on behalf of another player
    type: boolean
    default: op
  Magic.commands.wand:
    description: Player may create a wand
    type: boolean
    default: op
  Magic.commands.wand.wand:
    description: Player may create a specific wand
    type: list
  Magic.commands.wand.override:
    description: Player may configure wand overrides
    type: boolean
    default: op
  Magic.commands.wand.list:
    description: Player may list available wand templates
    type: boolean
    default: op
  Magic.commands.wand.describe:
    description: Player may describe their wand
    type: boolean
    default: op
  Magic.commands.wand.enchant:
    description: Player may turn an item into a wand
    type: boolean
    default: op
  Magic.commands.wand.unenchant:
    description: Player may destroy a wand
    type: boolean
    default: op
  Magic.commands.wand.add:
    description: Player may add a spell to a wand
    type: boolean
    default: op
  Magic.commands.wand.add.spell:
    description: Player may add a specific spell to a wand for another player
    type: list
  Magic.commands.wand.add.material:
    description: Player may add a specific material to a wand
    type: boolean
    default: op
  Magic.commands.wand.organize:
    description: Player may organize their wand
    type: boolean
    default: op
  Magic.commands.wand.configure:
    description: Player may set wand properties
    type: boolean
    default: op
  Magic.commands.wand.combine:
    description: Player may add wand template to their wand
    type: boolean
    default: op
  Magic.commands.wand.upgrade:
    description: Player may upgrade wand properties
    type: boolean
    default: op
  Magic.commands.wand.fill:
    description: Player may fill a wand with all spells
    type: boolean
    default: op
  Magic.commands.wand.remove:
    description: Player may remove a spell from a wand
    type: boolean
    default: op
  Magic.commands.wand.name:
    description: Player may name a wand
    type: boolean
    default: op
  Magic.commands.wand.duplicate:
    description: Player may duplicate an existing wand
    type: boolean
    default: op
  Magic.commands.wand.restore:
    description: Player may restore their bound wand
    type: boolean
    default: op
  Magic.commands.wand.unlock:
    description: Player may unlock a locked wand
    type: boolean
    default: op
  Magic.commands.wandp:
    description: Player may create a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.wand:
    description: Player may create a specific wand for another player
    type: list
  Magic.commands.wandp.override:
    description: Player may configure wand overrides for another player
    type: boolean
    default: op
  Magic.commands.wandp.add:
    description: Player may add a spell to a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.add.spell:
    description: Player may add a specific spell to a wand for another player
    type: list
  Magic.commands.wandp.add.material:
    description: Player may add a specific material to a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.configure:
    description: Player may set wand properties for another player
    type: boolean
    default: op
  Magic.commands.wandp.organize:
    description: Player may organize another player's wand
    type: boolean
    default: op
  Magic.commands.wandp.combine:
    description: Player may add wand template to another player's wand
    type: boolean
    default: op
  Magic.commands.wandp.describe:
    description: Player may describe their wand
    type: boolean
    default: op
  Magic.commands.wandp.upgrade:
    description: Player may upgrade wand properties for another player
    type: boolean
    default: op
  Magic.commands.wandp.fill:
    description: Player may fill a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.remove:
    description: Player may remove a spell from a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.name:
    description: Player may name a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.enchant:
    description: Player may turn an item into a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.unenchant:
    description: Player may destroy a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.duplicate:
    description: Player may duplicate an existing wand held by another player
    type: boolean
    default: op
  Magic.commands.wandp.restore:
    description: Player may restore another player's bound wand
    type: boolean
    default: op
  Magic.commands.wandp.unlock:
    description: Player may unlock an existing wand held by another player
    type: boolean
    default: op
  Magic.commands.magic:
    description: Player may reload the configuration
    type: boolean
    default: op
  Magic.commands.magic.load:
    description: Player may reload the configuration
    type: boolean
    default: op
  Magic.commands.magic.save:
    description: Player may save data
    type: boolean
    default: op
  Magic.commands.magic.clearcache:
    description: Player may clears the image and schematic caches
    type: boolean
    default: op
  Magic.commands.magic.cancel:
    description: Player may cancel any pending construction jobs
    type: boolean
    default: op
  Magic.commands.magic.commit:
    description: Player may clear all player undo queues
    type: boolean
    default: op
  Magic.commands.magic.list:
    description: Player may list general Magic info
    type: boolean
    default: op
  Magic.commands.magic.list.wands:
    description: Player may list lost wands
    type: boolean
    default: op
  Magic.commands.magic.list.maps:
    description: Player may list map images
    type: boolean
    default: op
  Magic.commands.magic.list.automata:
    description: Player may list stored automata
    type: boolean
    default: op
  Magic.commands.magic.list.tasks:
    description: Player may list running tasks
    type: boolean
    default: op
  Magic.commands.magic.clean:
    description: Player may remove lost wands from the world
    type: boolean
    default: op
  Magic.commands.magic.give:
    description: Player may give themselves special wand items
    type: boolean
    default: op
  Magic.commands.magic.sell:
    description: Player may give themselves items and their value
    type: boolean
    default: op
  Magic.commands.magic.worth:
    description: Player may check the value of an item
    type: boolean
    default: op
  Magic.commands.magic.describe:
    description: Player may check Mage attributes
    type: boolean
    default: op
  Magic.commands.magic.configure:
    description: Player may modify Mage attributes
    type: boolean
    default: op
  Magic.wand.use:
    description: The player may use a wand
    default: true
    type: boolean
  Magic.wand.destruct:
    description: A wand will self-destruct if the players tries to use it without permission.
    default: false
    type: boolean
  Magic.wand.override_bind:
    description: A player may use a wand even if it is bound to another player.
    default: op
    type: boolean
  Magic.wand.override_locked:
    description: A player may modify locked wands with wand commands.
    default: op
    type: boolean
  Magic.bypass_pvp:
    description: A player always bypasses PVP checks
    default: op
    type: boolean
  Magic.bypass_build:
    description: A player always bypasses build checks
    default: op
    type: boolean
  Magic.bypass:
    description: A player always bypasses other permission checks
    default: op
    type: boolean
  Magic.cast:
    description: The spells a player may cast
    type: list
  Magic.protected:
    description: The spells a player is immune to
    type: list