name: Magic
main: com.elmakers.mine.bukkit.plugins.magic.MagicPlugin
version: 2.8.2
website: http://mine.elmakers.com
author: NathanWolf
description : Mmmmmmaaaaagic!
softdepend: [WorldGuard, Essentials, dynmap]
load: startup
commands:
  cast:
    description: Cast a spell directly
    usage: cast <spellname> [parameters]
    permission: Magic.commands.cast
  castp:
    description: Cast a spell directly on another player
    usage: cast <player> <spellname> [parameters]
    permission: Magic.commands.cast
  spells:
    description: List all the spells you know
    usage: spells [category]
    permission: Magic.commands.spells
  wand:
    description: Create and modify wands
    usage: /wand [add|remove|upgrade|configure] [spell]
    permission: Magic.commands.wand
  wandp:
    description: Create and modify wands for another player
    usage: /wandp <player> [add|remove|upgrade|configure] [spell]
    permission: Magic.commands.wandp
  magic:
    description: Administer the Magic plugin
    usage: /magic [reload|populate]
    permission: Magic.commands.magic
permissions:
  Magic.commands.spells:
    description: Player may list spells
    type: boolean
    default: op
  Magic.commands.cast:
    description: Player may cast command-line spells
    type: boolean
    default: op
  Magic.commands.castp:
    description: Player may cast command-line spells on behalf of another player
    type: boolean
    default: op
  Magic.commands.wand:
    description: Player may create a wand
    type: boolean
    default: op
  Magic.commands.wand.wand:
    description: Player may create a specific wand
    type: list
  Magic.commands.wand.list:
    description: Player may list available wand templates
    type: boolean
    default: op
  Magic.commands.wand.add:
    description: Player may add a spell to a wand
    type: boolean
    default: op
  Magic.commands.wand.add.spell:
    description: Player may add a specific spell to a wand for another player
    type: list
  Magic.commands.wand.add.material:
    description: Player may add a specific material to a wand
    type: boolean
    default: op
  Magic.commands.wand.configure:
    description: Player may set wand properties
    type: boolean
    default: op
  Magic.commands.wand.upgrade:
    description: Player may upgrade wand properties
    type: boolean
    default: op
  Magic.commands.wand.fill:
    description: Player may fill a wand with all spells
    type: boolean
    default: op
  Magic.commands.wand.remove:
    description: Player may remove a spell from a wand
    type: boolean
    default: op
  Magic.commands.wand.name:
    description: Player may name a wand
    type: boolean
    default: op
  Magic.commands.wandp:
    description: Player may create a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.wand:
    description: Player may create a specific wand for another player
    type: list
  Magic.commands.wandp.add:
    description: Player may add a spell to a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.add.spell:
    description: Player may add a specific spell to a wand for another player
    type: list
  Magic.commands.wandp.add.material:
    description: Player may add a specific material to a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.configure:
    description: Player may set wand properties for another player
    type: boolean
    default: op
  Magic.commands.wandp.upgrade:
    description: Player may upgrade wand properties for another player
    type: boolean
    default: op
  Magic.commands.wandp.fill:
    description: Player may fill a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.remove:
    description: Player may remove a spell from a wand for another player
    type: boolean
    default: op
  Magic.commands.wandp.name:
    description: Player may name a wand for another player
    type: boolean
    default: op
  Magic.commands.magic.reload:
    description: Player may reload the configuration
    type: boolean
    default: op
  Magic.commands.magic.populate:
    description: Player may populate the world with chests
    type: boolean
    default: op
  Magic.wand.use:
    description: The player may use a wand
    default: true
    type: boolean
  Magic.cast:
    description: The spells a player may cast
    type: list