#
# This setup is meant to add directly to the vanilla survival experience.
#
# - Wands can be crafted on a crafting table using a blaze rod and nether star
# - Wands can be found in random naturally-spawned chests (block populator disabled by default- enable prior to world generation for best use!)
# - Wands can be upgraded on an enchanting table
# - Wands can be combined on an anvil
# - Wands are indestructible (and will show up on a dynmap)
# - Wands can be purchased in Essentials shops
# - WorldGuard building protection will prevent construction spell use
#

# Crafting settings for crafting wands
enable_crafting: true

# Whether wands can be combined on an anvil
enable_combining: true

# Whether wands can be upgraded on an enchanting table
enable_enchanting: true

# Whether or not using a wand on an anvil will organize its inventory
enable_organizing: true

# Allow wands to be purchased on Essentials' signs, if present.
enable_essentials_signs: true

# If set to non-zero, represents a time (in milliseconds) after which all construction
# spells will be reversed.
auto_undo: 0

# Wands are indestructible
indestructible_wands: true

# Update dynmap when constructing, if dynmap is present.
dynmap_update: true

# Show wands as dynmap markers, if dynmap is present
dynmap_show_wands: true

# Enable worldguard protection against construction spells
region_manager_enabled: true
