#
# Set up for an Avatar (bending) server.
#

# This is a complete wand/spell overhaul
load_default_spells: true
disable_default_spells: true
load_default_wands: false
load_default_enchanting: false
load_default_crafting: false

# Don't allow crafting
enable_crafting: false

# Don't allow combining
enable_combining: false

# Whether wands can be upgraded on an enchanting table
enable_enchanting: false

# Wands don't glow because they don't in the movies
wand_glow: false

# Effects from from the hands
wand_location_offset_vertical: -0.5

# Use the bending RP
default_resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-bending-RP-6.zip"

# We haven't yet updated this RP to have item-based icons.
url_icons_enabled: true