#
# Set up for an Avatar (bending) server.
#

# This is a complete wand/spell overhaul
load_default_spells: true
disable_default_spells: true
load_default_wands: true
disable_default_wands: true
load_default_classes: true
load_default_paths: false
load_default_crafting: false

# Don't allow crafting
enable_crafting: false

# Don't allow combining
enable_combining: false

# Disable the enchantment table showing the spell shop or upgrades
enchant_block: ""

# Wands don't glow because they don't in the movies
wand_glow: false