#
# Set up for a Harry Potter server.
#
# Crafting is not allowed, it is assumed each player has one wand
# they will keep throughout their play experience.
#

# This is a complete wand/spell overhaul
load_default_spells: false
load_default_wands: false
load_default_enchanting: false
load_default_crafting: false

# Quickly expiring items for performance
age_dropped_items: 240000

# Don't allow crafting
enable_crafting: false

# Don't allow combining
enable_combining: false

# Whether wands can be upgraded on an enchanting table
enable_enchanting: false

# Whether or not using a wand on an anvil will organize its inventory
enable_organizing: true

# Wands don't need to glow, because Dr00bles is awesome
wand_glow: false

# Wands will auto-bind to their owner
enable_binding: true

# Spells cannot be dropped out of wands
allow_spell_dropping: false

# We're going to asssume you're running a patched CB...
enable_custom_item_hacks: false

# Change the upgrade item
wand_upgrade_item: arrow

# Magic items don't work quite right if they have an enchanting path
default_wand_path: