#
# Set up for an RPG-style server, with different classes for players to choose from.
#

custom_currency:
 ap:
  max: 100
  default: 20
  icon: skull:http://textures.minecraft.net/texture/b11206551e723c356c23b32383abd19e6d7e9e5988f191e7866ae89ed6cb24
