base:
  storage:
    mana: class
    mana_max: class
    mana_regeneration: class
    mana_regeneration: class
    mana_timestamp: class
    spell_levels: class
    spells: class
    brushes: class
    path: subclass
    hotbar_count: subclass
    attributes: mage

