train_item:
  item:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_PICKAXE
    damage: 12
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      Unbreakable: true
      display-name: §aSteam Engine

