
# Set this to true to add the cooldown timers on skills
# This will involve scanning players' hotbars all the time, even
# when not holding wands.
live_hotbar_skills: true

# Use the flat skull RP if you're still using skull icons
default_resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/flat-skulls.zip"

# Turn off basically all of Magic's features
enable_crafting: false
enable_enchanting: false

# Skip loading all configs
load_default_wands: false
load_default_paths: false
load_default_spells: false
load_default_items: false
load_default_mobs: false

# Use this to turn off disabled icon URLs when using skull icons
# disabled_icon_url: ""

