#
# Base templates
# These are used to specify defaults for wands and other magic items.
#
base_wand:
    hidden: true
    drop: toggle
    left_click: cast
    right_click: none
    swap: cycle_hotbar
    quiet: 1
    bound: true
    keep: true
    undroppable: true
    indestructible: true
    effect_bubbles: false
    attributes:
      GENERIC_ATTACK_SPEED: 10
    attribute_slot: mainhand
  
base_sword:
    hidden: true
    drop: toggle
    left_click: none
    right_click: none
    swap: cycle_hotbar
    quick_cast: true
    quiet: 1
    bound: true
    keep: true
    undroppable: true
    indestructible: true

base_lightsaber:
    icon_inactive: wood_hoe:14
    icon_inactive_delay: 500
    drop: toggle
    left_click: none
    right_click: none
    swap: cycle_hotbar
    quick_cast: true
    mana_max: 50
    mana: 50
    mana_regeneration: 5
    protection_physical: 0.5
    block_reflect_chance: 0.5
    block_chance: 1
    block_fov: 0.5
    block_mage_cooldown: 3000
    quiet: 1
    bound: true
    keep: true
    undroppable: true
    indestructible: true
    effect_bubbles: false
    active_effects: true
    effect_sound: magic.saberhum
    effect_sound_interval: 700
    attributes:
      GENERIC_ATTACK_DAMAGE: 10
    effects:
        open:
        -  class: EffectSingle
           sound: magic.saberon
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
        close:
        -  class: EffectSingle
           sound: magic.saberoff
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
        swing:
        -  class: EffectSingle
           sound: magic.saberswing
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
        hit_entity:
        -  class: EffectSingle
           sound: magic.saberhit
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
        hit_block:
        -  class: EffectSingle
           sound: magic.saberhit
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
        hit_blocked:
        -  class: EffectSingle
           sound: magic.saberhit
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
        spell_blocked:
        -  class: EffectSingle
           sound: magic.saberhit
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
        spell_reflected:
        -  class: EffectSingle
           sound: magic.saberhit
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
             
