#
# Base templates
# These are used to specify defaults for wands and other magic items.
#
base_bound:
  hidden: true
  bound: true
  keep: true
  invulnerable: true
  immortal: true
  track: true
  undroppable: true
  indestructible: true

base_wand:
    hidden: true
    inherit: base_bound
    mode: inventory
    drop: toggle
    left_click: cast
    right_click: none
    swap: cycle_hotbar
    quiet: 1
    effect_bubbles: false
    attributes:
      GENERIC_ATTACK_SPEED: 10
    attribute_slot: mainhand
  
base_sword:
    hidden: true
    inherit: base_bound
    mode: inventory
    drop: toggle
    left_click: none
    right_click: none
    swap: cycle_hotbar
    quick_cast: true
    quiet: 1

base_lightsaber:
    hidden: true
    inherit: base_bound
    mode: inventory
    icon_inactive: wood_hoe:14
    icon_inactive_delay: 500
    drop: toggle
    left_click: none
    right_click: none
    swap: cycle_hotbar
    quick_cast: true
    mana_max: 50
    mana: 50
    mana_regeneration: 5
    protection_physical: 0.5
    block_reflect_chance: 0.5
    block_chance: 1
    block_fov: 0.5
    block_mage_cooldown: 3000
    block_cooldown: 5000
    quiet: 1
    effect_bubbles: false
    active_effects: true
    effect_sound: magic.saberhum
    effect_sound_interval: 225
    attributes:
      GENERIC_ATTACK_DAMAGE: 10
    effects:
        open:
        -  class: EffectSingle
           sound: magic.saberon
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: VortexEffect
             iterations: 10
             grow: 0.06
             radius: 0.2
             offset: 0,-0.8,0
             pitch: -60
             particle: redstone
        close:
        -  class: EffectSingle
           sound: magic.saberoff
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: VortexEffect
             iterations: 10
             grow: 0.06
             radius: 0.2
             offset: 0,0.5,0
             pitch: 60
             particle: redstone
        swing:
        -  class: EffectSingle
           sound: magic.saberswing
           sound_volume: 1
           location: origin
           use_wand_location: true
           effectlib:
             class: VortexEffect
             iterations: 6
             circles: 1
             helixes: 2
             grow: 0.1
             radius: 0.1
             offset: 0,0.5,0
             pitch: 20
             particle: fireworks_spark
        hit_entity:
        -  class: EffectSingle
           sound: magic.saberhit
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
        hit_block:
        -  class: EffectSingle
           sound: magic.saberhit
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
        hit_blocked:
        -  class: EffectSingle
           sound: magic.saberhit
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
        spell_blocked:
        -  class: EffectSingle
           sound: magic.saberhit
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
        spell_reflected:
        -  class: EffectSingle
           sound: magic.saberhit
           sound_volume: 1
           location: origin
           color_override: color
           use_wand_location: true
           effectlib:
             class: HelixEffect
             iterations: 1
             radius: 0.3
             particle: redstone
             
