#
# Use this configuration if you want to use the official Magic resource pack.
#
# This will make the default want a wooden sword, which has a custom icon
# in the resource pack.
#
# The resource pack will also modify the look of command blocks, to
# make Automata more interesting.
#

wand_item: wood_hoe